# https://github.com/Homebrew/homebrew-bundle
brew 'autoconf'
brew 'automake'
brew 'texinfo'
brew 'gnuplot'
brew 'hdf5'
# brew 'qt@5'
brew 'curl'
brew 'xz'
brew 'icoutils'
brew 'glpk'
brew 'bison'
brew 'pcre2'
brew 'qrupdate'
brew 'qhull'
brew 'readline'
brew 'fftw'
brew 'fltk'
brew 'gl2ps'
brew 'suite-sparse'
brew 'openblas'
brew 'gawk'
brew 'gnu-sed'
brew 'arpack'
brew 'ghostscript'
brew 'freetype'
brew 'fontconfig'
# brew 'gcc' https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
# brew 'gfortran'
brew 'libsndfile'
brew 'libtool'
brew 'portaudio'
# brew 'qscintilla2'
brew 'sundials'
